
if(NOT DEFINED AMP_COMPILER_IS_GCC_COMPATIBLE)
    if(CMAKE_COMPILER_IS_GNUCXX)
        set(AMP_COMPILER_IS_GCC_COMPATIBLE ON)
    elseif(MSVC)
        set(AMP_COMPILER_IS_GCC_COMPATIBLE OFF)
    elseif("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang")
        set(AMP_COMPILER_IS_GCC_COMPATIBLE ON)
    endif()
endif()

